import { createUseStyles } from 'react-jss'
import LoginForm from '../../components/auth/login/form'
import Head from "next/head";
import useWindowSize from "../../utilities/hooks/useWindowSize";

const useStyles = createUseStyles((theme) => ({
    root: {
        padding: [theme.spacing * 2, 0],
        minHeight: ({height}) => height ? height : 'auto',
        ...theme.utils.flexbox.center
    },
    card: {
        width: '100%',
        padding: theme.spacing * 3,
        textAlign: 'center',
        ...theme.utils.flexbox.center,
        flexFlow: 'column',
        gap: theme.spacing * 10,
        [theme.mediaQueries.mUp]: {
            ...theme.card,
            width: 600,
            margin: 'auto',
        }
    },
    title: {
        ...theme.pageStyle.title,
    },
    subtitle: {
        ...theme.pageStyle.sectionTitle,
    },
    forgotPassword: {
        marginBottom: theme.spacing * 2
    },
}))

const Login = () => {
    const { height } = useWindowSize()
    const classes = useStyles({height})


    return <>
        <Head>
            <title>Login | Next</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={classes.root}>
            <div className={classes.card}>
                <div>
                    <h5 className={classes.title}>Log In to your account</h5>
                    <p className={classes.subtitle}>
                        Enter the data required to Log In
                    </p>
                </div>
                <LoginForm />
                {/*<div>
                    <p className={classes.forgotPassword}>
                        <Link to={routeNames.FORGOT_PASSWORD}>
                            Forgot your password?
                        </Link>
                    </p>
                    <p>
                        Don't have an account yet?{' '}
                        <Link to={routeNames.SIGNUP}>Sign Up</Link>
                    </p>
                </div>*/}
            </div>
        </div>
    </>
}

export default Login
