import Head from 'next/head'

const Profile = () => {
    return (
        <div>
            <Head>
                <title>Profile | Next</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Profile</h1>
            </main>
        </div>
    )
}

export default Profile;